# Generated by Django 5.1.7 on 2025-03-15 00:20

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=16, unique=True, validators=[book.models.validate_ibns]),
        ),
    ]
