# Generated by Django 5.1.7 on 2025-03-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'disponível'), ('on_loan', 'emprestado')], default='available', max_length=10),
        ),
    ]
